cc_library(
    name = "election_compare",
    hdrs = ["election_compare.hpp"],
    srcs = ['election_compare.cpp'],
    deps = [
        "@fcpp//lib:beautify",
        "@fcpp//lib/coordination:election",
        "@fcpp//lib/coordination:geometry",
    ],
    visibility = [
        '//visibility:public',
    ],
)
