cc_binary(
    name = "experiment",
    srcs = ["experiment.cpp"],
    deps = [
        "@fcpp//lib:fcpp",
        "//fcpp:election_compare",
    ],
)

cc_binary(
    name = "parameter",
    srcs = ["parameter.cpp"],
    deps = [
        "//cpp:func",
    ],
)
